### PR TITLE
Refactor codebase - separate out API calls, restructure project

### PR DESCRIPTION
**Pull request by kungpaogao**
### Summary 

This pull request is a major step in the refactoring the Android code base, with the ultimate goal of implementing Android architecture into our app (#21).

- Restructured project - created folders for each "component" as well as utility folders
- Separated out API calls to `API.kt` (significantly reduced importance of `BaseActivity`)
- Removed a lot of overrides - using lambdas (for now) instead of having to reason with inheritance
- Changed all API calls to route through `API.kt` as well as the response structure (using lambdas)
- Began work on decoupling Firebase authentication (#30)

### Test Plan 

Application behaves almost exactly as before. The only difference is how we retrieve the data. See breaking changes below.

### Breaking Changes  

- Bugs from previous PRs still exist (#26)
- The failure page does not display on network connection errors (#31) - this is related to the order to retrieve Firebase's `idToken`, make requests, and subsequently update the UI, so we won't fix for now

### CODE REVIEW

**Comment by SamChou19815** [comment]
@kungpaogao I further cleanup the stuff in API class. Now things are finally readable here and I managed to get rid of all subsequent API calls in FacilitiesActivity.

**Comment by SamChou19815** [comment]
@kungpaogao merge?

**Comment by kungpaogao** [comment]
We're going to add `onError` to the other requests and then merge.

**Comment by kungpaogao** [comment]
The failure page is broken right now and doesn't display after the 10s delay (#31).

**Comment by kungpaogao** [comment]
I have referenced the issue in the PR comment, but we won't fix #31 for now.

**Pull request merged**
